services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: myApi-backend
    ports:
      - "5063:5063"
    environment:
      Authentication__Google__ClientId: ${GoogleClientId}
      Authentication__Google__ClientSecret: ${GoogleClientSecret}
      Authentication__GitHub__ClientId: ${GitHubClientId}
      Authentication__GitHub__ClientSecret: ${GitHubClientSecret}
      ASPNETCORE_HTTP_PORTS: 5063
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${Database};Username=${Username};Password=${Password}"
      Jwt__Key: ${JWT_KEY:?JWT_KEY is required}
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:5063/health || exit 1"] 
     interval : 30s
     timeout :  5s
     retries : 3
     start_period  : 10s
    depends_on:
       db:
        condition: service_healthy 

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${Database}
      POSTGRES_USER: ${Username}
      POSTGRES_PASSWORD: ${Password}
   
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${Username} -d ${Database}"]
      interval: 50s
      timeout: 30s
      retries: 3
      start_period: 20s
volumes:
  database:
