// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApiBlya.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620172803_AddUserIsBlocked")]
    partial class AddUserIsBlocked
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.HasKey("Id");

                    b.ToTable("histories");
                });

            modelBuilder.Entity("MyApiBlya.Services.Permissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("Id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("MyApiBlya.Services.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isblocked");

                    b.Property<string>("JwtToken")
                        .HasColumnType("text")
                        .HasColumnName("jwttoken");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text")
                        .HasColumnName("provideruserid");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshTokenExpiresAt");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refreshToken");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyApiBlya.Services.usersPerm", b =>
                {
                    b.Property<int>("users_id")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.Property<int>("perms_id")
                        .HasColumnType("integer")
                        .HasColumnName("perms_id");

                    b.HasKey("users_id", "perms_id");

                    b.HasIndex("perms_id");

                    b.ToTable("users_permissions", (string)null);
                });

            modelBuilder.Entity("UsersHistory", b =>
                {
                    b.Property<int>("actions_id")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<int>("users_id")
                        .HasColumnType("integer")
                        .HasColumnName("user");

                    b.HasKey("actions_id", "users_id");

                    b.HasIndex("users_id");

                    b.ToTable("UsersHistory");
                });

            modelBuilder.Entity("MyApiBlya.Services.usersPerm", b =>
                {
                    b.HasOne("MyApiBlya.Services.Permissions", "permissions")
                        .WithMany("users")
                        .HasForeignKey("perms_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApiBlya.Services.User", "user")
                        .WithMany("perms")
                        .HasForeignKey("users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permissions");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UsersHistory", b =>
                {
                    b.HasOne("History", "history")
                        .WithMany("users")
                        .HasForeignKey("actions_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApiBlya.Services.User", "user")
                        .WithMany("histories")
                        .HasForeignKey("users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("history");

                    b.Navigation("user");
                });

            modelBuilder.Entity("History", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("MyApiBlya.Services.Permissions", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("MyApiBlya.Services.User", b =>
                {
                    b.Navigation("histories");

                    b.Navigation("perms");
                });
#pragma warning restore 612, 618
        }
    }
}
